### ISSUE TITLE
Reduce data in song list

### ISSUE THREAD

**Issue by relick** [relick/touhou-song-sorter#13]
There's some data in the song list that, now songs are directly associated with title objects, could be transferred to the title objects. This would help reduce the massive amount of copy/paste noise in the song data list.
There will need to be a way to override however to allow e.g. the bonus CD category to have multiple album names, so this is not quite as straightforward as just moving the data.

**Comment by kaleemullah786** [comment]
hey i would like to contribute. can you provide more details

**Comment by relick** [comment]
You can take a look at fnc_data_song.js if you'd like more context of what I'm talking about. Each song entry duplicates a lot of data about its associated game and that data could be merged into the title list.

**Comment by relick** [comment]
f39d37083e5f506294e0727d2d687d5c01e094ec
