### ISSUE TITLE
Filter by Zun / Non-Zun compositions?

### ISSUE THREAD

**Issue by BenDTU** [relick/touhou-song-sorter#6]
It'd be neat if you could filter by whether Zun is the composer or not - I'd like to rank everything he's written but not necessarily include things like the Fighting game stage themes.

Happy to help code that in if needed.

**Comment by relick** [comment]
Sounds like a cool idea. I don't have much time to make improvements like that to the sorter so if you could give it a try it would be much appreciated!

**Comment by BenDTU** [comment]
Can do, I'm most of the way through getting that working I think. Would a 'Zun compositions only' tickbox be sufficient? That would largely just exclude songs from the spinoffs from other composers including remixes from other composers, but would still include things like 'Futatsuiwa from Gensokyo' and 'Adventures of the Lovestruck Tomboy', which are technically arrangements of existing songs but still done by Zun.

**Comment by relick** [comment]
I'd say your description of that tickbox fits more titled as 'ZUN's arrangements only'. 'Compositions' would imply that the remixes should be included. Both possibilities would fill a niche the sorter doesn't yet offer, though, I don't want to impose work on you but maybe offering both would be best. But if you just want to do the arrangements filter as described, that's fine too.

**Comment by BenDTU** [comment]
Ah yeah you're right, Zun Arrangements would be better

**Comment by BenDTU** [comment]
Got a PR up for that one now, let me know what you think.
